src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Entity\Traits\RecipeSerializerTrait;
use App\Repository\RecipeRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RecipeRepository::class)
 */
class Recipe implements \JsonSerializable
{
    use RecipeSerializerTrait;

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $ingredient;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    private $portions;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     */
    private $preparation_time;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="recipes")
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIngredient(): ?string
    {
        return $this->ingredient;
    }

    public function setIngredient(string $ingredient): self
    {
        $this->ingredient = $ingredient;

        return $this;
    }

    public function getPortions(): ?int
    {
        return $this->portions;
    }

    public function setPortions(int $portions): self
    {
        $this->portions = $portions;

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparation_time;
    }

    public function setPreparationTime(int $preparation_time): self
    {
        $this->preparation_time = $preparation_time;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('ingredient')
            ->add('portions')
            ->add('preparation_time')
            ->add('photo')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/Api/RecipeController.php
<?php

namespace App\Controller\Api;

use App\Entity\Recipe;
use App\Helper\Factory\RecipeFactory;
use App\Repository\RecipeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

/**
 * @Route("/api/recipes")
 */
class RecipeController extends AbstractController
{
    /**
     * @var RecipeRepository
     */
    private $recipeRepository;
    /**
     * @var RecipeFactory
     */
    private $recipeFactory;
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * RecipeController constructor.
     * @param RecipeRepository $recipeRepository
     * @param RecipeFactory $recipeFactory
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(RecipeRepository $recipeRepository, RecipeFactory $recipeFactory, EntityManagerInterface $entityManager)
    {
        $this->recipeRepository = $recipeRepository;
        $this->recipeFactory = $recipeFactory;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route(name="api_recipe", methods={"GET"})
     */
    public function index(): Response
    {
        $recipes = $this->recipeRepository->findAll();
        return $this->json($recipes);
    }

    /**
     * @Route("/{id}", name="api_recipe_show", methods={"GET"})
     */
    public function show(Recipe $recipe): Response
    {
        return $this->json($recipe);
    }

    /**
     * @param Request $request
     * @return Response
     * @Route(name="api_recipe_create", methods={"POST"})
     */
    public function create(Request $request): Response
    {
        $recipe = $this->recipeFactory->createEntity($request->getContent());
        $this->entityManager->persist($recipe);
        $this->entityManager->flush();
        return $this->json($recipe, Response::HTTP_CREATED);
    }

    /**
     * @param int $id
     * @param Request $request
     * @param Recipe $recipe
     * @return Response
     * @Route("/{id}", name="recipe_api_update", methods={"PUT","PATCH"})
     */
    public function update(int $id, Request $request, Recipe $recipe): Response
    {
        $recipe = $this->recipeFactory->updateEntity( $recipe, $request->getContent());
        $this->entityManager->persist($recipe);
        $this->entityManager->flush();

        return $this->json($recipe);
    }

    /**
     * @param int $id
     * @param Recipe $recipe
     * @return Response
     * @Route("/{id}", name="recipe_api_delete", methods={"PUT","DELETE"})
     */
    public function delete(Recipe $recipe): Response
    {
        $this->entityManager->remove($recipe);
        $this->entityManager->flush();
        return $this->json($recipe);
    }

}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\Recipe;
use App\Form\RecipeType;
use App\Repository\RecipeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/recipes")
 */
class RecipeController extends AbstractController
{
    /**
     * @var RecipeRepository
     */
    private $recipeRepository;
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * RecipeController constructor.
     * @param RecipeRepository $recipeRepository
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(
        RecipeRepository $recipeRepository,
        EntityManagerInterface $entityManager
    ){

        $this->recipeRepository = $recipeRepository;
        $this->entityManager = $entityManager;
    }

    /**
     * @Route("/", name="recipe_index", methods={"GET"})
     */
    public function index(): Response
    {
        return $this->render('recipe/index.html.twig', [
            'recipes' =>  $this->recipeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="recipe_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $recipe = new Recipe();
        $form = $this->createForm(RecipeType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $recipe = $form->getData();
            $this->entityManager->persist($recipe);
            $this->entityManager->flush();
            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('recipe/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recipe_show", methods={"GET"})
     */
    public function show(Recipe $recipe): Response
    {
        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="recipe_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Recipe $recipe): Response
    {
        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->entityManager->flush();

            return $this->redirectToRoute('recipe_index');
        }

        return $this->render('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="recipe_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Recipe $recipe): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {
            $this->entityManager->remove($recipe);
            $this->entityManager->flush();
        }

        return $this->redirectToRoute('recipe_index');
    }
}

templates/recipe/_delete_form.html.twig
<form method="post" action="{{ path('recipe_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recipe/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button type="submit" class="btn btn-primary">Save</button>
{{ form_end(form) }}

templates/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recipe{% endblock %}

{% block body %}
    <h1>Edit Recipe</h1>

    {{ include('recipe/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('recipe_index') }}">back to list</a>

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe index{% endblock %}

{% block body %}
    <h1>Recipe index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Ingredient</th>
                <th>Portions</th>
                <th>Preparation_time</th>
                <th>Photo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for recipe in recipes %}
            <tr>
                <td>{{ recipe.id }}</td>
                <td>{{ recipe.name }}</td>
                <td>{{ recipe.description }}</td>
                <td>{{ recipe.ingredient }}</td>
                <td>{{ recipe.portions }}</td>
                <td>{{ recipe.preparationTime }}</td>
                <td>{{ recipe.photo }}</td>
                <td>
                    <a href="{{ path('recipe_show', {'id': recipe.id}) }}">show</a>
                    <a href="{{ path('recipe_edit', {'id': recipe.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('recipe_new') }}">Create new</a>
{% endblock %}

templates/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recipe{% endblock %}

{% block body %}
    <h1>Create new Recipe</h1>

    {{ include('recipe/_form.html.twig') }}

    <a href="{{ path('recipe_index') }}">back to list</a>
{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipe{% endblock %}

{% block body %}
    <h1>Recipe</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ recipe.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ recipe.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ recipe.description }}</td>
            </tr>
            <tr>
                <th>Ingredient</th>
                <td>{{ recipe.ingredient }}</td>
            </tr>
            <tr>
                <th>Portions</th>
                <td>{{ recipe.portions }}</td>
            </tr>
            <tr>
                <th>Preparation_time</th>
                <td>{{ recipe.preparationTime }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ recipe.photo }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('recipe_index') }}">back to list</a>

    <a href="{{ path('recipe_edit', {'id': recipe.id}) }}">edit</a>

    {{ include('recipe/_delete_form.html.twig') }}
{% endblock %}